filegroup(
    name = "gcl_cc",
    srcs = glob(["*.cc"]),
    visibility = ["//visibility:public"],
)

filegroup(
    name = "gcl_h",
    srcs = glob(["*.h"]),
    visibility = ["//visibility:public"],
)
