filegroup(
    name = "regexp_cc",
    srcs = glob(["*.cc"]),
    visibility = ["//visibility:public"],
)

filegroup(
    name = "regexp_h",
    srcs = glob(["*.h"]),
    visibility = ["//visibility:public"],
)
