filegroup(
    name = "meadowlark_cc",
    srcs = glob(["*.cc"]),
    visibility = ["//visibility:public"],
)

filegroup(
    name = "meadowlark_h",
    srcs = glob(["*.h"]),
    visibility = ["//visibility:public"],
)
