#ifndef COTTONTAIL_SRC_NULL_IDX_H_
#define COTTONTAIL_SRC_NULL_IDX_H_

// English stopword list originally developed for TREC CAsT 2019.
// Oriented towards conversational question answering.
namespace cottontail {
std::vector<std::string> cast2019_stopwords = {
    "a",           "about", "an",    "and",  "any",    "are",     "as",
    "at",          "be",    "being", "by",   "can",    "defines", "describe",
    "description", "did",   "do",    "does", "for",    "from",    "give",
    "had",         "has",   "have",  "his",  "how",    "i",       "if",
    "in",          "is",    "isn",   "it",   "its",    "like",    "many",
    "may",         "me",    "much",  "my",   "of",     "on",      "once",
    "one",         "ones",  "or",    "s",    "should", "so",      "some",
    "such",        "t",     "tell",  "than", "that",   "the",     "their",
    "them",        "there", "these", "they", "this",   "to",      "use",
    "using",       "was",   "we",    "well", "were",   "what",    "when",
    "where",       "which", "who",   "why",  "will",   "with",    "you",
    "your",
};

// English stopword list derived from spaCy.
std::vector<std::string> spaCy_stopwords = {
    "a",          "about",      "above",      "across",     "after",
    "afterwards", "again",      "against",    "all",        "almost",
    "alone",      "along",      "already",    "also",       "although",
    "always",     "am",         "among",      "amongst",    "amount",
    "an",         "and",        "another",    "any",        "anyhow",
    "anyone",     "anything",   "anyway",     "anywhere",   "are",
    "around",     "as",         "at",         "back",       "be",
    "became",     "because",    "become",     "becomes",    "becoming",
    "been",       "before",     "beforehand", "behind",     "being",
    "below",      "beside",     "besides",    "between",    "beyond",
    "both",       "bottom",     "but",        "by",         "ca",
    "call",       "can",        "cannot",     "could",      "d",
    "did",        "do",         "does",       "doing",      "done",
    "down",       "due",        "during",     "each",       "eight",
    "either",     "eleven",     "else",       "elsewhere",  "empty",
    "enough",     "even",       "ever",       "every",      "everyone",
    "everything", "everywhere", "except",     "few",        "fifteen",
    "fifty",      "first",      "five",       "for",        "former",
    "formerly",   "forty",      "four",       "from",       "front",
    "full",       "further",    "get",        "give",       "go",
    "had",        "has",        "have",       "he",         "hence",
    "her",        "here",       "hereafter",  "hereby",     "herein",
    "hereupon",   "hers",       "herself",    "him",        "himself",
    "his",        "how",        "however",    "hundred",    "i",
    "if",         "in",         "indeed",     "into",       "is",
    "it",         "its",        "itself",     "just",       "keep",
    "last",       "latter",     "latterly",   "least",      "less",
    "ll",         "m",          "made",       "make",       "many",
    "may",        "me",         "meanwhile",  "might",      "mine",
    "more",       "moreover",   "most",       "mostly",     "move",
    "much",       "must",       "my",         "myself",     "n",
    "name",       "namely",     "neither",    "never",      "nevertheless",
    "next",       "nine",       "no",         "nobody",     "none",
    "noone",      "nor",        "not",        "nothing",    "now",
    "nowhere",    "of",         "off",        "often",      "on",
    "once",       "one",        "only",       "onto",       "or",
    "other",      "others",     "otherwise",  "our",        "ours",
    "ourselves",  "out",        "over",       "own",        "part",
    "per",        "perhaps",    "please",     "put",        "quite",
    "rather",     "re",         "really",     "regarding",  "s",
    "same",       "say",        "see",        "seem",       "seemed",
    "seeming",    "seems",      "serious",    "several",    "she",
    "should",     "show",       "side",       "since",      "six",
    "sixty",      "so",         "some",       "somehow",    "someone",
    "something",  "sometime",   "sometimes",  "somewhere",  "still",
    "such",       "t",          "take",       "ten",        "than",
    "that",       "the",        "their",      "them",       "themselves",
    "then",       "thence",     "there",      "thereafter", "thereby",
    "therefore",  "therein",    "thereupon",  "these",      "they",
    "third",      "this",       "those",      "though",     "three",
    "through",    "throughout", "thru",       "thus",       "to",
    "together",   "too",        "top",        "toward",     "towards",
    "twelve",     "twenty",     "two",        "under",      "unless",
    "until",      "up",         "upon",       "us",         "used",
    "using",      "various",    "ve",         "very",       "via",
    "was",        "we",         "well",       "were",       "what",
    "whatever",   "when",       "whence",     "whenever",   "where",
    "whereafter", "whereas",    "whereby",    "wherein",    "whereupon",
    "wherever",   "whether",    "which",      "while",      "whither",
    "who",        "whoever",    "whole",      "whom",       "whose",
    "why",        "will",       "with",       "within",     "without",
    "would",      "yet",        "you",        "your",       "yours",
    "yourself",   "yourselves",
};
} // namespace cottontail
#endif // COTTONTAIL_SRC_NULL_IDX_H_
