load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "splade-annotate",
    srcs = [
      "splade-annotate.cc",
    ],
    deps = [
      "//src:cottontail",
    ] ,
    linkopts = [
      "-pthread",
    ],
)

cc_binary(
    name = "splade",
    srcs = [
      "splade.cc",
    ],
    deps = [
      "//src:cottontail",
    ],
    linkopts = [
      "-pthread",
    ],
)

cc_binary(
    name = "c4-build",
    srcs = [
      "c4-build.cc",
    ],
    deps = [
      "//src:cottontail",
    ],
    linkopts = [
      "-pthread",
    ],
)

cc_binary(
    name = "dagstuhl",
    srcs = [
      "dagstuhl.cc",
    ],
    deps = [
      "//src:cottontail",
    ],
    linkopts = [
      "-pthread",
    ],
)

cc_binary(
    name = "dagstuhl-trec45",
    srcs = [
      "dagstuhl-trec45.cc",
    ],
    deps = [
      "//src:cottontail",
    ],
    linkopts = [
      "-pthread",
    ],
)

cc_binary(
    name = "dynamic-test",
    srcs = [
      "dynamic-test.cc",
    ],
    deps = [
      "//src:cottontail",
    ],
    linkopts = [
      "-pthread",
    ],
)

cc_binary(
    name = "idx-timing",
    srcs = [
      "idx-timing.cc",
    ],
    deps = [
      "//src:cottontail",
    ],
    linkopts = [
      "-pthread",
    ],
)

cc_binary(
    name = "mt",
    srcs = [
      "mt.cc",
    ],
    deps = [
      "//src:cottontail",
      "//third_party/linenoise",
    ],
    linkopts = [
      "-pthread",
    ],
)

cc_binary(
    name = "pref2train",
    srcs = [
      "pref2train.cc",
    ],
    deps = [
      "//src:cottontail",
    ],
    linkopts = [
      "-pthread"
    ],
)

cc_binary(
    name = "qap",
    srcs = [
      "qap.cc",
    ],
    deps = [
      "//src:cottontail",
    ],
    linkopts = [
      "-pthread",
    ],
)

cc_binary(
    name = "rag2024-extract",
    srcs = [
      "rag2024-extract.cc",
    ],
    deps = [
      "//src:cottontail",
    ],
    linkopts = [
      "-pthread",
    ],
)

cc_binary(
    name = "ssr-timing",
    srcs = [
      "ssr-timing.cc",
    ],
    deps = [
      "//src:cottontail",
    ],
    linkopts = [
      "-pthread",
    ],
)

cc_binary(
    name = "treccast20",
    srcs = [
      "treccast20.cc",
    ],
    deps = [
      "//src:cottontail",
    ],
    linkopts = [
      "-pthread",
    ],
)

cc_binary(
    name = "treccast20-build",
    srcs = [
      "treccast20-build.cc",
    ],
    deps = [
      "//src:cottontail",
    ],
    linkopts = [
      "-pthread",
    ],
)

cc_binary(
    name = "treccast21",
    srcs = [
      "treccast21.cc",
    ],
    deps = [
      "//src:cottontail",
    ],
    linkopts = [
      "-pthread",
    ],
)

cc_binary(
    name = "treccast21-build",
    srcs = [
      "treccast21-build.cc",
    ],
    deps = [
      "//src:cottontail",
    ],
    linkopts = [
      "-pthread",
    ],
)

cc_binary(
    name = "treccast22",
    srcs = [
      "treccast22.cc",
    ],
    deps = [
      "//src:cottontail",
    ],
    linkopts = [
      "-pthread",
    ],
)

cc_binary(
    name = "treccast22-build",
    srcs = [
      "treccast22-build.cc",
    ],
    deps = [
      "//src:cottontail",
    ],
    linkopts = [
      "-pthread",
    ],
)

cc_binary(
    name = "trecdl21",
    srcs = [
      "trecdl21.cc",
    ],
    deps = [
      "//src:cottontail",
    ],
    linkopts = [
      "-pthread",
    ],
)

cc_binary(
    name = "wikidata-build",
    srcs = [
      "wikidata-build.cc",
    ],
    deps = [
      "//src:cottontail",
    ] ,
    linkopts = [
    ],
)

cc_binary(
    name = "scratch",
    srcs = [
      "scratch.cc",
    ],
    deps = [
      "//src:cottontail",
    ],
    linkopts = [
      "-pthread",
    ],
)
